image: docker

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

stages:
  - test
  - publish

test:
  stage: test
  services:
    - name: docker:dind
      alias: docker

  before_script:
    - apk add --update alpine-sdk curl docker-compose openjdk11 postgresql-client

    - ./tools/install-waitforit.sh
    - ./tools/install-golang.sh
    - ./tools/install-sonarscanner.sh
    - export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
    - export GOPATH=$HOME/go
  script:
    - go mod verify
    - go mod download
    - golangci-lint run ./...

    - waitforit -address=tcp://docker:2375 -timeout=30
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u="$CI_REGISTRY_USER" --password-stdin
    - docker-compose up -d

    - ./tools/wait.sh

    - source test.env
    - go test -run TestAutowpMigrations
    - go test -run TestTrafficMigrations
    - docker exec -t goautowp_mysql_test sh -c "mysql -uroot --host=127.0.0.1 --port=3306 -ppassword autowp < /dump.sql"
    - go test -v -race -coverprofile=cov.out
    - gotestsum --junitfile report.xml --format testname -- -race
    - sonar-scanner -Dsonar.login=$SONARCLOUD_TOKEN
    #- goveralls -service=gitlab
  artifacts:
    reports:
      junit: report.xml

publish:
  stage: publish
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - ./tools/install-waitforit.sh
  script:
    - waitforit -address=tcp://docker:2375 -timeout=30
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u="$CI_REGISTRY_USER" --password-stdin
    - docker build -f build/package/Dockerfile . -t $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE;
  only:
    - master
