image: $CI_REGISTRY/autowp/runner-base-image

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

stages:
  - test
  - publish

test:
  stage: test
  services:
    - name: docker:dind
      alias: docker

  before_script:
    - export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
    - export GOPATH=$HOME/go
  script:
    - go mod verify
    - go mod download
    - golangci-lint run ./... -v --timeout 10m

    - waitforit -address=tcp://docker:2375 -timeout=30
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u="$CI_REGISTRY_USER" --password-stdin
    - docker-compose up -d

    - ./tools/wait.sh

    - source test.env
    - go test -run TestAutowpMigrations
    - go test -run TestPostgresMigrations
    - docker exec -t goautowp_mysql_test sh -c "mysql -uroot --host=127.0.0.1 --port=3306 -ppassword autowp < /dump.sql"
    - gotestsum --junitfile report.xml --format testname -- -coverprofile=cov.out -covermode count ./...
    - gocover-cobertura < cov.out > coverage.xml
    - sonar-scanner -Dsonar.login=$SONARCLOUD_TOKEN
    - npx semantic-release
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
  interruptible: true
  rules:
    - if: $CI_COMMIT_TAG !~ /^v\d.*/

publish:
  stage: publish
  services:
    - name: docker:dind
      alias: docker
  before_script:

    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
    - waitforit -address=tcp://docker:2375 -timeout=30
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u="$CI_REGISTRY_USER" --password-stdin
    - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
  script:
    - sentry-cli releases new "$CI_COMMIT_TAG" || true

    - docker pull "$CI_REGISTRY_IMAGE" || true
    - docker build -f build/package/Dockerfile . -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" -t autowp/goautowp:$CI_COMMIT_TAG
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - docker push autowp/goautowp:$CI_COMMIT_TAG

    - git clone -b master https://gitpush:${GITPUSH_TOKEN}@gitlab.pereslegin.ru/autowp/helm.git
    - cd helm
    - ../tools/update-helm-chart.sh
    - git push origin master

    - sentry-cli releases finalize "$CI_COMMIT_TAG" || true
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d.*/
  environment:
    name: production
    url: https://www.wheelsage.org/

publish-master-to-github:
  stage: publish
  before_script:
    - mkdir -p /root/.ssh
    - touch /root/.ssh/known_hosts
    - chmod 0600 ~/.ssh/known_hosts
    - cat "$SSHKEY" > ~/.ssh/id_rsa
    - chmod 0400 ~/.ssh/id_rsa
    - ssh-keygen -R github.com
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
  script:
    - git checkout -b "$CI_COMMIT_BRANCH"
    - git remote add github git@github.com:autowp/goautowp.git
    - git push github "$CI_COMMIT_BRANCH"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
