image: docker

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

stages:
  - build

build:
  stage: build
  services:
    - name: docker:dind
      alias: docker

  before_script:
    - apk add --update alpine-sdk curl docker-compose postgresql-client

    - ./tools/install-waitforit.sh
    - ./tools/install-golang.sh
    - ./tools/install-sonarscanner.sh
  script:
    - go mod verify
    - go mod download
    - golangci-lint run ./...

    - waitforit -address=tcp://docker:2375 -timeout=30
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u="$CI_REGISTRY_USER" --password-stdin
    - docker-compose up -d

    - ./tools/wait.sh

    - docker logs goautowp_mysql_test

    - source test.env
    - go test -run TestAutowpMigrations
    - go test -run TestTrafficMigrations
    - docker exec -it goautowp_mysql_test sh -c "mysql -uroot --host=127.0.0.1 --port=3306 -ppassword autowp < /dump.sql"
    - go test -v -race -coverprofile=cov.out
    - sonar-scanner -Dsonar.login=$SONARCLOUD_TOKEN
    - goveralls -service=travis-ci

    - docker build -f build/package/Dockerfile . -t $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE;
  only:
    - master
