run:
  timeout: 10m
  allow-parallel-runners: true
issues:
  exclude-files:
    - spec_grpc.pb.go
    - spec.pb.go
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    #- cyclop
    - decorder
    #- depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    #- exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    #- funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    #- gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    #- gocognit
    - goconst
    - gocritic
    #- gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    #- ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    #- nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    #- tagliatelle
    - tenv
    - testableexamples
    - testifylint
    #- testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - usetesting
    - wastedassign
    - whitespace
    #- wrapcheck
    - wsl
    - zerologlint
  disable:
    - typecheck
    - exportloopref
linters-settings:
  mnd:
    ignored-numbers:
      - '2'
      - '2.0'
  varnamelen:
    min-name-length: 2
    ignore-names:
      - i
      - j
      - k
  gomoddirectives:
    replace-allow-list:
      - github.com/doug-martin/goqu/v9
