sudo: required

language: go

services:
  - docker

go:
  - "1.10"

addons:
  sonarcloud:
    organization: "autowp-github"
    token:
      secure: $SONARCLOUD_TOKEN

install: true

before_script:
  - sudo service mysql stop
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go mod verify

  - curl -L https://raw.githubusercontent.com/alecthomas/gometalinter/master/scripts/install.sh > gometalinter-install.sh
  - chmod +x ./gometalinter-install.sh
  - ./gometalinter-install.sh -b $GOPATH/bin

  - go get -u github.com/mattn/goveralls
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.12.5

script:
  - gometalinter --deadline 2m -D gocyclo || travis_terminate 1;
  - golangci-lint run --enable-all || travis_terminate 1;

  - docker-compose up -d
  - wget -q -O ./waitforit https://github.com/maxcnunes/waitforit/releases/download/v2.4.1/waitforit-linux_amd64
  - chmod +x ./waitforit
  - source test.env
  - ./waitforit -address tcp://$AUTOWP_RABBITMQ_HOST:$AUTOWP_RABBITMQ_PORT -timeout 30 || travis_terminate 1;
  - go test -v -race -coverprofile=cov.out || travis_terminate 1;
  - sonar-scanner -Dsonar.login=$SONARCLOUD_TOKEN || true;
  - goveralls -service=travis-ci || travis_terminate 1;

  - go build -ldflags "-s -w" -o build/package/goautowp cmd/goautowp/goautowp.go || travis_terminate 1;
  - cp -R migrations build/package/migrations
  - docker build build/package/ -t $DOCKER_REPO || travis_terminate 1;

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_REPO;
    fi

