sudo: required

language: go

services:
  - docker

go:
  - "1.15"

addons:
  sonarcloud:
    organization: "autowp-github"
    token:
      secure: $SONARCLOUD_TOKEN

install: true

before_script:
  - sudo service mysql stop
  - go mod verify
  - go mod download

  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
  - go get -u github.com/mattn/goveralls

script:
  - golangci-lint run ./... || travis_terminate 1;

  - docker-compose up -d
  - wget -q -O ./waitforit https://github.com/maxcnunes/waitforit/releases/download/v2.4.1/waitforit-linux_amd64
  - chmod +x ./waitforit
  - source test.env
  - ./waitforit -address tcp://localhost:5672 -timeout 30 || travis_terminate 1;
  - go test -v -race -coverprofile=cov.out || travis_terminate 1;
  - sonar-scanner -Dsonar.login=$SONARCLOUD_TOKEN || true;
  - goveralls -service=travis-ci || travis_terminate 1;

  - go build -ldflags "-s -w" -o build/package/goautowp cmd/goautowp/goautowp.go || travis_terminate 1;
  - cp -R migrations build/package/migrations
  - docker build build/package/ -t $DOCKER_REPO || travis_terminate 1;

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_REPO;
    fi

