sudo: required

dist: focal

language: go

services:
  - docker
  - rabbitmq
  - mysql

go:
  - "1.15"

addons:
  sonarcloud:
    organization: "autowp-github"
    token:
      secure: $SONARCLOUD_TOKEN
  apt:
    packages:
    - rabbitmq-server

install: true

before_script:
  - sudo service mysql stop
  - go mod verify
  - go mod download

  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
  - go get -u github.com/mattn/goveralls

script:
  - golangci-lint run ./... || travis_terminate 1;

  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker-compose -f docker-compose-travis.yml up -d || travis_terminate 1;
  - wget -q -O ./waitforit https://github.com/maxcnunes/waitforit/releases/download/v2.4.1/waitforit-linux_amd64 || travis_terminate 1;
  - chmod +x ./waitforit
  - source test.env
  - ./waitforit -address tcp://localhost:5672 -timeout 30 || travis_terminate 1;
  - ./waitforit -address tcp://localhost:3306 -timeout 30 || travis_terminate 1;
  - sleep 5
  - go build -o app cmd/goautowp/goautowp.go
  - ./app migrate
  - docker exec -it goautowp_mysql_test sh -c "mysql -uroot --host=127.0.0.1 --port=3306 -ppassword autowp < /dump.sql" || travis_terminate 1;
  - go test -v -race -coverprofile=cov.out || travis_terminate 1;
  - sonar-scanner -Dsonar.login=$SONARCLOUD_TOKEN || true;
  - goveralls -service=travis-ci || travis_terminate 1;

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -f build/package/Dockerfile . -t $DOCKER_REPO || travis_terminate 1;
    docker push $DOCKER_REPO;
    fi

