version: '2'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: goautowp_rabbitmq_test
    restart: always
    ports:
    - "5672:5672"
    - "15672:15672"

  mysql:
    image: mysql:8
    container_name: goautowp_mysql_test
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=autowp
    ports:
    - "3306:3306"
    volumes:
    - "./test/dump.sql:/dump.sql:ro"

  nginx:
    image: nginx
    container_name: goautowp_nginx_test
    restart: always
    ports:
    - "80:80"
    volumes:
    - "./test:/usr/share/nginx/html:ro"

  postgres:
    image: postgres:13
    container_name: goautowp_postgres_test
    restart: always
    environment:
      - POSTGRES_DB=traffic
      - POSTGRES_USER=traffic
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  keycloak:
    image: jboss/keycloak
    container_name: goautowp_keycloak_test
    restart: always
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /tmp/realm.json
      JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.upload_scripts=enabled"
    volumes:
      - ./test/realm.json:/tmp/realm.json
    ports:
      - "8081:8080"
