version: '2'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: goautowp_rabbitmq_test
    ports:
    - "5672:5672"
    - "15672:15672"

  mysql:
    image: mysql:8
    container_name: goautowp_mysql_test
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=autowp
    ports:
    - "3306:3306"

  nginx:
    image: nginx
    container_name: goautowp_nginx_test
    ports:
    - "80:80"
    volumes:
    - "./test:/usr/share/nginx/html:ro"
